---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rmq-user-public-api
  namespace: banking-data
spec:
  encryptedData:
    password: AgAhpVEHOrtNE26DHwMaV5uUuwefp367pLqUxtmaivaUb/yBxEoldTUTsRjHpnWxi65MDICL6dNLj05+waTU1s7xtvtmF3vwVwtLKw3ZoI0VL5SxSSGhLqyONYKWbuAcox/DTZMOjMNGLrmxIs44Iq/TRbvOao7hoZxIXhUQsNGoH6hcJepxrXE2dcbHM06RBSeOn3LS8AuAVz2T3+s6HsGjNaN+Hnlqo/NCzS5TTJeutBGIjQGpWIuFJ4/E4AjxiHADwY3dfTzohsCtX7FUNuIaeglzntZppktl/eBdHpXs32y76Mad92+Y0amWIe7cTNUZFjvDfHV9OGQa/Dy0dva5FE+SC1bpIEY9d/EvxQGmVZVfCrUe8OrzHWbNDn7b1ITW+wVfSNqANSc+jfuXWtoyz08EfwkUHPr2r1/Zyp7HPln0qO+RCEZvs8REOenWxOpwUzwm5F/T0fvXf/H8GyQNngkLJEzE5K+rT5CZuLE50J3ESeIOfa7s1AHG4Q7GAYhNa7hrU6VGTvelCikAHkPkD1uEaUXxHBd32qyg61WgROoscv/zj2MQ8AJQoEi81OrrH3sb58UgsCHXTz8isSb9OmMTIz9Fy+i0uALYzmbtvT6dD1qt6+sj3M0BzS1ZyXzM5iCj1YQLOb1YwcykSbHLlAM/cT7i+Wycd2aXMBDyE4P/SkMk8FZo4xau6QDhCUpvqCA0vqrTYHKtu00XcPkCXTS/VYSJgjU96s6wgIWB3nSJ/wFBOqnafcSVT9jfHwI=
    username: AgA9mtoje4RdsxdNU6b4v1AdX/9TeE/hVx0Qs+/XWE0viZjm+xyYvLeDLO6p/c8L1w10qa/nW2rBpV/WzsUB+4k2nyUkXbl0PMrXiGnDpepvSiiPd5Fb+Y6zFyd2J8V62ZvF/Mji7vdOj0dNzMX7HROWHn8iyOdwP0peOMgonDh3QVehRJGGddxRUhV1DexbTkvlYW9qP4L98O2PXItIPwhFzHCH+ITGfMGD4aTfdRYFn++2QXHPgH3SDPxwJWXfEfhn72s/BGoi2B6drsiW1m+sN69/KCEwUXTrqpwKvPnHwrGEul4NUDW0EZjqE8/qH/UDC5RmJCEDa9Phn5ETj4JVyX2o/6P1j5CtgbepBcP2t+M01cr6b5l6E58reaZqFa07IDAD5WMAsSj9c5cZTUMANZ9tFmR5HXaPELGucmFSQCRMCydzVc+CVCpNUxkIR85eFKYJm52KBlVGzJENzx5OJxxVyofkX/hPh8HvhnLNFYwEaPszMmXWhFxOnZKc9G53wM+4MCZPswvUn8TZ41CiehrqJrKPKnScR3mc2B9kZy3fOY4vfbrMzCXwMk47dWy38uRRzndNzeMuEb5MkQfykYGyDcUGrMd6QYx+xAei6Xp1IW5jfAkZrzx14HanHIvbjEXKkEvX50rY18s7qZu/KWAJ/sNbETwXcI+nhE6cnZWzVSpgQDvdztwTGanlwCHUfF4SeEQM8goQ
  template:
    metadata:
      labels:
        rabbitmq.com/topology-operator: "true"
      name: rmq-user-public-api
      namespace: banking-data
