---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-admin-app
  namespace: banking-data
spec:
  encryptedData:
    password: AgAUBCvsZ33k3q9Qy972ojxh8RhUVHNPPKRtAh5bT7krhwhRzguL0SDyP4ujxyD0c/70Q2bcClgx4vId6M2rI0BRXSPWirAR7Mmaug0FmYBRCXslfYu6b+IsJ5rkuxbtGXgXmd12Mryh/hSZ++wEyRYVtnbPPnC8iRJctMKPK3Tfk9XeFfiYEEb6kqjJkCJNopD+/O0ytkCZcoABDsGA+hE6DyV8d/1AaAYud6hUyP+3qjBpUy7iJ2dfFpTyeBIjlN+RO83iEBWw7wm6DKYbqgJq0rSTJl9Sjkjm4HmKbG6t3eYoajtXuJGdtlpL3DbWPJT40HX1eF9/FLG47dBbetNuNf2tusUuL0UJONQRkEX+OkMwfJBsgP5rCLmd0EBaGZ80XdxD8E77fhX45bKKV5ffb5xe65WDirLZ3YZnLEMpNK0egDRs0sDUOrQOgTLEuFXTU5jz8nD9MOdT9pVAVoCRCKtbupGKRXjTgBuUyqq/UzGndMoOZWVLxqTVMqwe+6F7sK2pIcXM83fsow2OoHQzQNfmNUZsQurJ1J405LSrdpKXb7BSDZPBA2450sGkNcNdc7X7824tyQdU5+CEsS9UEdEuopxoNhl7BAPTeacJ4n6UD1oPHcYKhrqtIQxNhIgH540kfmnYhwgjkXFanS9TZ3z68uqmuSj8gtRXNuothZbn43H+GXkpwmutBzRy9hcIBjBn8CuIupUNLkxPCwq29VEkK7nQv5IDsbLT9jnkzHV2WLkrjN49vkOTiUmI/aE=
    username: AgDexjkYj9EIvpPpPU5fd3w3pJ42mioCLJUlv5PM2RdA2XWeeTWRkjAFIrhf+BFq9lOoRbZREYqdz+VqVNmFlimRIgXF1y2Ye+0WXeEJoDK9pJJVpGPNnYm8Rg18vX8IwUiWt07g5GXi9mC0eYgF7lMQLtQwyMialIp4tpQce+aH+vvoGXb+2mAgQq7SGBLjs9/Z8VDbfQYp2VyJmDv1wTdxFPbm4NLnV2hYs4Lf3Th4rVKi/de7gcNqrNVzqP6Tup+a3Xj7uEDQJLCziC1Sf/+zfNjZtDNg0ttiReboltR1NpYlklJeKH24odPt90PL7ih4EteG5fEmMU5W0dbh1R4pzt8KHvZwlobqovdqhXoFMYAYGVJT6U8KOUGpLp673TNb9M6mDf/pDiydF31xnjv/EXaEoBkbMRh6fJKzrc9N+OTgXgKiLOgsEpz+ZUAEnx1OxKEpCGZgUCEUKsxE+ayPJa4bCw2RppJM11JrcyLoO4TozRYkTb2i/sdM07GhYO4EDZ3g/CPOp77pJABV3GoiX2jU3yGloF4FYxthetnHrzhaxbYCDLSQ18eBNWGnBIIzyAaWsJs6hjkQZvKE81WpXHm1P4xHHuNIa8pZVs75hTIkW3Al/WIrBCSxuwTjxJK+X3OvDiGnpeckmdMky4d1CWPBloltSuZxQehTjwlAk7NukP9EszxlLQAQTiKyGFIEcMx2KTizjVM=
  template:
    metadata:
      name: pg-admin-app
      namespace: banking-data
    type: kubernetes.io/basic-auth
