---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: public-api-migrator-dsn
  namespace: banking
spec:
  encryptedData:
    dsn: AgBwSb4VrtjSKW60OIVrpqNf7iZSOmpPtRH3IXoZlqBOWpY7Q+Ouzk4xLQQxQK1s64e8YOzSj7kOAj5tPKwrTf2YGuIHp9kGako6Spkn+7ulIcMYsfYDO1fenpmxeDasaQUf+Ulryv07CXj+x0VuZ1F7cciqj/nNaiZx3dsPPpS84kL3ITDM4VoBNXEfxNIb4/pYxfbEB2GH4DEW5U7AwxYgtu8+lPimZFPS0/FkWa2vap5QsfQ1/BE/Kg3/v3yTEmDNK1Y2G5G8IxjXKkjihIUQ2Fna7sl6qIdvpPirGVAfdCcr29Ug+JsfKSALIFMUAVfETBsa8Vj88PjtGIhi+379Wz4ERYyV0rJ70qDBrnS8Q8OmnM8jEHk4Gz0P0sPAASn5zJa65U8MXpnYFOkzLE/O4FfUJ6x47KhCdFzaQMym2AnKvftWMEzvownshv+HtxQ0Mz+4V3bs5wL77Br1mXqPzW7+t8hZGG2RSVj8spuDrWzv+2qSjkObHfqzl23X+1loAuJd6R6+6Ff6hwxXkv5u/eloq4K9BPRiJ1OvUwDeYZi/pknRHrr8N0sULsjJ4x6aN230Cm3P4tfw20BHfEfrcB1h8h1M0G1bjP33cgYOmIaL5Xw3sxVi0mIfd0URrjHA2i1LkOxK6Hf9t4dKhN0cNqt0GJByvam0LnmRn/GAQSJXETfsQ3NWzbGFss4NNvQRLlMZ5PV6K5EMx8g6SytZHYVSdnfjVOaBASLFKS3GM5E+sq15LRJ/azmfgjhiag8JJklhl6Ns+VMkyFiFeYYXup8VS3pJ5eYw4dNelOO3I7vcTf5q45ug4DnwcAD1OSgcKH2WE09+l8XyXXAKfC4iHrhiEVoOo8/fypVbNeA=
  template:
    metadata:
      name: public-api-migrator-dsn
      namespace: banking
