---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-api-migrator-dsn
  namespace: banking
spec:
  encryptedData:
    dsn: AgAG/RSJhqodyM50mQiKzi4dYyng3F4tKFFe3rU38C7JT/qbP3U/ut3WndPaeb/BEKfJgug0Ip933zlBiPQysy+UEQU6NpZ+aQ2/AMGbNdD6h2ffPMB4L3ke9r1++UENddJCbb+I+SsmpHGNRSE8Iiaj8+eo96dywW4p4epGFEnx7sW3YO+5UzpTMTJPuNDWE1pKhUhrbxku6JzFrMKCiMpMSr8OVBRD+sAe+8V245iArYNjgOnySAX+Ia0bjBO/0GaSzrNF5X5UtnApg2Ta3TgQ9OFDCwocOg6AMZkzh5Qdi8JXNbDU963J91deWSXqmxB6+1KIobs1fVVccEAyhAesd3ONuv41yyTiO+OBI+eAWRlynfDGSJybN+dXbZHpIRyHzUmrwlkQv3tQfPpLUSzzAO4JzhedWh/Q9MSAn1gMnvG67jhkIZIKmNHgtX8VsLP5/Zd7P59xpY+NU0taEnRN2IkZL4vlLn+hhcmeMQkrR92Wj7zDSYeEwixIgFaAsxy5uuwbOX2DEgybU3V3E3EIR0qijAWPNyhYIt1Rl4qdZdvyhiDk361PLOaOyGoTb2yEOWUbOy864KKS7+WHejDUn9AFyj0Y38n6UwZbLY0+pFWpqR8hKdUgrWzUiqTkK5IJHNw6K2H4re68HrKeYyPOCofqzpL/BWpp+TUBZUifFACE3/yFZ080F0I+ae+CIixg380wIfWDEQheuAUnG3kZWjrxfVG85iYL8W0E213xInzTC4omh+PlfuNRDSpDn3rdquUlBnGc+zSTAU1HFqUKHdYnMUfRF3D1cj8gFgChc0pLUn0/0THIOcqPgKlBXgIPADzRr4s/E/JwlDkPyqJ1u+phX658hEQgyEID
  template:
    metadata:
      name: admin-api-migrator-dsn
      namespace: banking
