---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: core-migrator-dsn
  namespace: banking
spec:
  encryptedData:
    dsn: AgAbuHw8J1rYc5RM8Yr73o41MFaUXPlXiIdnjMwrKjyxlmtMXWqz0m3DL+CSUUqxnpD4a+ORxpBw7Qe4ifNuEsqLg8VsrCH7yx0BLPhhNaVRnwWKxn376syCVbCWFxRqQ+60ZC8zZwG2pT073HxbLd+8LQFPxIMmb0CvDqXS7H2vKtGjigey5qOT5Ub9Jw9aD6xJ99/k66wX6HZP3CyeBRa56AbUusvR7J0YOwDscZ2KvdI/PRaVY2cCzqPsvvqOag28DmFNyqsMSDlbTSo8p+hkSketUAoq9p1S+zdpHL1vLW4nsVg0V28bcRLmAQDN6ZWXoGwRN79IG4aJ+ZpX18n1yunW9opxjv9y1oSKDJ7e8ZjTe2fZYHEvLWSeC02YaiXlDHuh1Mx5wtH3HA7Owu95hGxXyFXd+upSFiKmpOTXTMHsZmyvc99FgM+9o7u1WzDOJoWk0uqiO7o2IVqi2LgNYtU5IOCsYm+fPxvH4ftF7pYU4zXDffKpPjNY7Ju2BhMJKz/5HtuBniMDqVJ+HtJbjQETI93/oBZGto3lmTCRKoDGSuTKoPFVm9o0PWB9xCIIuFmkLvRv5qo3SpTvu+GF80TjVmaDqniKIzr7a4nZprdRRWEVh3vaMykMTXVTAdvXj2o8G0sMOHpeZhQ+LYR0brcGxVK/28nph0JckkinQ2uWKCWmL185FRWdoVOcaMyqNcMphGzjiXGO3v0kj0mb4rhyveq+H4Pl1Nw6hfSHipt6yk+UDATRaI4gC/i1cTgeWDCg/lg5HMackiPGmB9dNO2rOM5Sq5GUfAxjinnmw9E0pSvGugakP8e5ijEjHS2ks80BFf7zVk/pUsx01LhZvx0RLhR160hHpg==
  template:
    metadata:
      name: core-migrator-dsn
      namespace: banking
