---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-core-app
  namespace: banking-data
spec:
  encryptedData:
    password: AgBzsFQr5osLmiNwG6mrHb8UiMHhQM8IDZ3tCQkwaqJApg2lPZvDyIzu+cIUJop4hmQxKJGD6DV1D0k931GX6cKIwe1aJyu09TUbKC/zB6Ywa4ywVt5f2+l34N8AQUMyiYEt7fdnP6XgH9Cc1qNzvtOwhKG7bdVOWDlotUmlSOUe8rIOYxTWxrGfC52VE+SpSVRT8Ko7xXdHtq7o63M+mQW65S98fhGtEg4QNQC4DnK/p0PsQND+eWQKb6tcla2QAK/vpp+JAoPgD7iWXwBJAr3cstUPABzJVyse1t8vlMS/g3lpj9Z1fUmyywEQMhxb5SPU4tM4A1q/GUdNk81uQGwtc+Ng8ZHKnRYrsxzhLIodEQaO4yk+VGbjrGGQu1wQpjmDNtgnIEMS0++IlznHQtL9LbuTV7u/tuB2So/pZV0xi2EEvaigFMPG3jk2VJMUJnYaR2yiQsWE+Gyq7bNOsmuJ4G8xww+2DZ/zAfbGmBkHPjqPqLC9JRc52fMbSa3MN3+lNgSLPkBLEEDWNHsX4Jqv25cOSOK+HnN0OsdZkqLEa6W7EWIbxK4Rt3E/eaDJaP+2u5mpwBnSS946uBjQWDQt5iGOT4s7ZtWuuT55tteRGqR9bMV7BGVDcSGCmuIib5r7dGb7Ll2rRzdSAYhiYX0Yn/5fqAnCwueaklag0IX5d+iTY9GfwkGAnRrmmCZq14k/KAi+XjaXstxGpxTVsjimG70jfPt+7jK4+1PKml5Vdy8GNi7x4dyuePdKUnwpivI=
    username: AgAPOVaw+LtpwUXfUgUfl3jLSgGP7wXDklOHqM08urFofT6waCJkrCJnhZh8OjVsKvBZNSqtL7/P1UtE6mTpJmDq2Xu+Zqbxc8OxRTkdRPa1OU/JIKWf2+Xo4UVSKD4DWD3sGmMglQIJ5KWyoGRsGh43QTl4m9oYH/qSaum0OXkDEC7lewRtkthgZoQ3BN/maxWNIo7K8pXIxEQtVy4zwiwVZKSaStlIkx1HPNGWsqa+86VQuesAFHWiWeSW3Itb5l1+Uc/0B8Y7wNkhKYxQk4dc3T6PKUss48QRsvtb0cdHli1V5GfnarADXwyoEgQSveYVqQDKKGahpAQS+3T/u2TqxpA8tK0BkAyuLZP4VUzQKWsScNnbU7VKr7l0qUbb5r74qqNUq7guwVHKOO/Zt0Q8yJIm7tu/xPjKLeow8JxYZCo8aMy3n/dLkS4+n7/sOkz8Ne9CimQHEuvbq1S9Tn6kgFYo4kKOQ9oQ4uLvKu5YPePY6stwI/h+eH6+CwChvUq3dSYUSBuVSNDfQvDuLc61qVjFXAvpfEPXBtph/vzpy9driBjXnz9UhacWcT/8/QRBMBpP0chUcFwohzergkOQwIufwRUrD/nG89lA2ODdZGMq/PbIj0CdJE37mfpPOIqGi9EBMFGOvWEQDGDdydVZdlimvdq3QrV7enqfJOlT60H4Dtlcd3NoSG02X0JH2SLh4JF8RUei7Q==
  template:
    metadata:
      name: pg-core-app
      namespace: banking-data
    type: kubernetes.io/basic-auth
