---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-core-migrator
  namespace: banking-data
spec:
  encryptedData:
    password: AgCE9e1+WIZn3WlKe1ncCuv1NPcBJ11B43xtSe4cC1gcInFvCZHsopRpDdvHXd0rTvIMTvyGZxlBwbhUPcyePSbhRyqknNDDVaPT5R5r4F4hMmlJff9bbFtMCdITCNe5YR3i2fm3dbm3yW+l+CKOPSmBA1x/ZaAY3UKycINqeFnAHk/vZTbffa6wALNVSwH0JUKPrZ3fHclVznjMG62roYoetvwR7nXxx/TusHobM6vmjI8BRXglPPNF2RQl4XP+fE1JjQOWx3U+5DWf6BZhmAaFmtUtjgrkq8ZmmDKseKTGmtBnSW0SPncCJN7jfvpCMoGc3g8ZEb3PzcZT4t+7LvmJkv9keHQhOB4Bg/0xwmtb4WRJYgHnhlZxkEq+duH125bJ2TfskonpWikIY5clSPxeDw4RmOLyuv5vyzDJIJsrDFu35HTzKj2z97yvj7tltJj2VvEA/qSj1M0KWaLXOxEyF3kt2X1Xu9rHbk2J1ked3yYZghFFmtI6EgL6BuT2NoDDLZeKe+gcRQ9Hn6PrsO8V/AwH2zhOdwkZXJGdOlTb9XsLm3Z2aTbGUjSs8I85gJ0TPgw7VbprDMszgeC18EZyKm2oU4hgwXtgGKK1SOdpvyTfvSr09NhnD0e1wUCTqElN5Hln+wIMD0cavu5vB6uKPkgnzRBwQyASizYyc4YFF5yLGelqO8WJ1W0WbP6nH0SJSLXvRcvESinh66aHGPzOV0tbMQnD2pZyHsF2PkFeXufzQyu+drVtwzSUxRrwnzM=
    username: AgDSkmy2dmHO4EhE3znDlOzX62Q601Wdh1ZylbijqbENs8eLSWGukG09EIZAju1YjKDHlHhYdMJjhxXYbfa4ODJLuuOm/0DH/avDog8I8AuUqKRbOM831oPDpsCPETtUnz6W6qV5NfDYdJSOAQjICvs0WQA2gVNreOXbP6RHYyvZXfHXXV0nIlOLjApA4JoHVHoL0pHaCt/7vcrWD9xw45duJDTctHAS7q3CslXgDAQLIPtQNZ0mhduLlFNj2wn4g18WhW0CPFxGkucAbl0Nhex++MhgpNNosNRnpyBxYhhfaXYwfE/prVPKWZ9hE9JE16I0rL4SXOsAZwOsy+iTR2x9bvDJxnVIOL8dhJayceHBO4qt/LqEUhsZ33mOqkSNEMZxRIKcIGFoOfsfEvb1fRYZb+NKBvs7WCbG42G1Vdx5xbsExXOGg1cFNuhBtzmd5r9zb8eMYhVzYI9JIW3bm+UsHWNBaIWVK2gUb0g396og1jsvmAvU3PJPxtD40MnEZOSZuzb+GcVVp1yUafSdA0L1oEBrfwgrXvJ2PfDzmZ9ANq/6dZ8uiPXlRky5Iu5gbdWhtXko4jYOPpSbB69sYxQw8eYoTpy/nIK0DQn5pLaWgyw46LcLGgDG2YTsUB5GvyISgOUTCJifmGAGUC5rmRpynEZ3hsIK5VOn/BHRIe7f9LVEZKdqrdFvn2mNBhlwWzNPpk/xJz4VdKlBpNxD
  template:
    metadata:
      name: pg-core-migrator
      namespace: banking-data
    type: kubernetes.io/basic-auth
