---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-public-migrator
  namespace: banking-data
spec:
  encryptedData:
    password: AgCySfIlkN4mSMuDxKBcrA3FUYmf7yjwlYxUiNOyssMweQHTZyhoeLmtg6hW9TMTrjr3TIzZ4uYIk/fHIFN4IzdY+RiV31I0WGEMSWCMw0wMgaCY0sKQurzvfvvmGdvD8LsEzVIXik4c6zYxVQ0MttVAGEOmFzD3OyFzBFBNz1R3J5FXDOSfQGh8Sm3HhybHmovMAhZ3izNvgOPGTa18ld+tg/wkZtxEaRGJjLJGnPDDClTqzZ1OVXVpcfHmKqyD4HEo2rYmaXqHFw12B60kxG3A4zviK/vu7ikRZU/4F2FKgHEBiQbWpvgmilqeBJfEqt35L1xbpp/MtJsuOh6n0JRh8486Jz3nJnZh4V+CkNHjE75LMNgtgAWwjQCIcx4TTiBwb+cMhtyawIdhmhSjOqvXy9njeNRa4irxlXGOFEvTnnpWYvLJg9uvgoFxm1Juv1TggG+TX37tdBRB3lzbYW8RL9ybyC17tCsXgWXvhDE4IlKxO+IVam1DAzNPWFqiaMxGuJRv5sDO7+VzT0CJYhJEqlrml+akaHWDXVIpF7wLbvRPZh+qff1epph0Zp1XqdmSy8fQlJrVodqZ1NaciZ12O+0ZLgCVBebFDL6t2T4P/XNog8Af2UbZKdIOGoW5i1WPOU8Ah4yv/YqhNYBEtiCz14R04Jh7qOSdv7y+Nq183b5D05M7ZmHvL2eJes/FJdadCDiaOVm5LhhYYnlOeGV+rcwbdJHRbtHicFjX/r12GD47SyoAXfPO2qUOh+F57WY=
    username: AgBXH45YWbApb9HNr2qJ1OsZlvWFbYioRss6X5t3qVoNua7/ADVmJdDopibNzluUeiUZjre/bMQ8c4kKbJztDwOMMsD/+ph2ed/bXP6jzU11G0jEiXzoPK1+qaCrP0zgieMiaww2sUpX8JfzpYTXYattHGCJJYJNeVa8usebQhvkfQj/n7/hQr0jrIHE9tX9iVp2T9BzMTh614AFBc/Ud/x+V8mMWhZDi8OpoRMhLXaiifA/kc2tARHMmsSxN/+KDJUK3i3JzI4v0hhNMogF++uDj+UcSHvduqt0YYRQKqBDYW3F3cGvmdQBptw8FO9MVKLrr17M5eIgXAm26xqzj/xMXQ3+g4RgLTtt2IBE8gMi/tubpTHoq1GRUfVxfkR4f1jPU2wk/FPZLpFzfDp3BnVYIvMy/7mX1uvIG5YZnG3Ae4SOIIn6mZD6bMODPX/zjjCYjVSzFSBoZOvhOhe2XaKe4UENb7cdhM+N+kTMz02toRNdIi6n0dc4srcVqGuZINnDYW4z+rS7rh+w7Xl7482mvyiPNbybd5c/yOqwIgaVGD1MSeQx0CcSEnmTPBU7BZFpIGbmigWSf5yQCmxUPszg7ykV3mkCrBXlh9fhdZhksGcLlrH/lbpfjW4eGRusfJqLgpbd8E9ciYm4zNoKTPrEqFAkIJ3fmOyhk/Ctdw6pI4417cqOSdZSbpVQ2kfi3H7XXVB444G6RCZ65WxzjmU=
  template:
    metadata:
      name: pg-public-migrator
      namespace: banking-data
    type: kubernetes.io/basic-auth
