---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-admin-migrator
  namespace: banking-data
spec:
  encryptedData:
    password: AgAvahVKTcwZKCr73y4clDjSVOzNbQx1/4tupcftbRsj8mWyYdDXhRydQaO6rhrtvzgoUUG4y7wDjBtivc9aCjHLlXgOMIfcEqHtOiI9EqLb7UMSxZtRahed2m+CiGlbJ/2QVl9bnb4Ia/5L0fxfuoVUj5U6fdPn6n0rP6XZzvCH63bOTeHSAawr/FyI++h2X1x8xN5ylhm3v2/M2cyx7VDCsfuAtCtv7jJHw9LS/HBKYibh03WVv1RC5lTYWoJjQ7DEDHao+9bMMphdldzLyhRGLDDgCBaS7uneqSoRpP1OLC8kNJYjkj6J/waR8AFAHZz0M5/UJjFQ0DR0dJArU/wRubZLrNgcFPkY6rh2V7UZqa+QTYBIimm67ClyalmPa/B8AHGh+5nKR8HHxHEJkfajnytovc7e/aVxy+goL4ho8dqhfYrDCNApfKZjvvfPT4egrirxOEFsFVuWbfaDKKuQeVJrXSWsSF0eGvYI48Xwj0xUHPtXB0etcnahvoSAKXBAEp6X+dKAxG2nLl9D9yxxNv96Vwt59f7txfLLhHxSF3KE/9Suds2pHmySJSBt79eg0a1/Obnreykv6o11D1mJeXctxj/6fJAo14qs6kNv3NL5AzjRBWFdtERKnfLHmRLVWMx2ZwXZF8PQyHT1zJXnAtiqMJdIljK6/+TA5uk65S8fs6zT1BUU7IyuNKAOLJt1Ci3GgIEkOsfwqJzsVSmHdufbPmLiT8eMf1CJPDZhyucQmfqBNrXRf0u8FlUtNio=
    username: AgCRLi9jXnPNBo+NHHGdgnwmoyKo7sXzLzjQAjrSxqMffsjLzy1i9IbsMqqFjYRkw0ES4zOn88cmfpC061cwdx5DQ6nUWpj2+9KDSf6ieVDJXEIit57iTY33YF/jy0TccTXzidasAHOlfDQmFtxJ3l4FXYX/mLSxtecG7ax9DAkAK9JnrmyNenOqy70b7EK62JzBHmFfpXZmACciHyTvzlTmjJzC/+wwyIPAULsWcWegTetEr4cvplm5l05LyXO6GNUdG4rDBdjkmEY5KQEjscOy/aTmS52G2QNjm6B78Tmfb2Fr5jMzs5TxQVQb0U9ST33rinIoNdL8oGa2EaGYKcXevK385eYvVortpO5nA6UCj8ebkwAvSkiz69qrJJUOF2SczQzbJQPf9ClgwGHXmSia9cww6JYqYG46qMiWTU5rcm3nR7eu2nyDH6h6Ut1MEdlDCFqyVSSyygtnBopIqZvXfrB4UhBeFX9DeAUq+xtBTbRfnram0wkRuM/50z0mN9QFdllwNb+U5iUtOm8N+QT7YYPWMGllu/GXEL2xTxkbO/3sKvdjf09yOlUyOTcI4N8PSCXjCdfbH8+VRtFOckyfXc7gTLqTpx7jOJipS1pdrkZ1TN3Ul3I/8qQ8ELUezSvNsYcAZQE1dOt3tpYy3DvL6oedMsArDylawakQFkXVLtZJQatiGcG9P0vg3JPKQ9INUMt8At+ktw0u2kxUBA==
  template:
    metadata:
      name: pg-admin-migrator
      namespace: banking-data
    type: kubernetes.io/basic-auth
