---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rmq-user-admin-api
  namespace: banking-data
spec:
  encryptedData:
    password: AgBIxJ37XA0MnCkTDVcvZbBZ841CLpEW+PZd93DiT8EtPi8mQbTK93MKnxq5Mae1Y2tS3oAwnZpx4m4/2+7p6wz81HpUpuXOGvAs8oZX6dxFXbFhLW6bzjXMf+rUU1n3e3+O2+y3Y+YCpAr9AGEvEupxEwFtl1ofoi9uSbWH3p9ha+Enknm9k20nNej6AnWW01js48rI0sZd0ZJ3waqxdp1iuOoEcOikIhELI2RQ00E8lrR/jP3BX5vQTCoIUxooY2UdTWd84nIAROMzOwtAMVCw0f0IlLt73LtKijaRDJG0QcCIYqRs7k0t/sozBRqlNYbwNDcJWiBzD5LLRw2e/qnkLD06qlu0Y8WoidHvKt6tFWuHmriRLIQo+UN3eDGMIXOMe+/j9cX29XrEzZzP5RKWs8BTBCLaTDK9P4EWHi1WS/Ma4lzyWkPAHs+49rjo6eClK18TdzmI0YUapS+UqQez025m18ActGqVMi8UPKWGh4di2z05FPFVAlzZX/M4I43nHue/5ZhQauUGeGvqyTHKkgJ9i+zyeLz+L6oVYR1homIeMNFeQ9Hvz2wDTRhBQtms15W2CcRNl01ja7hLlq8XCnVvY1TuBXHKQhsqoMLZILfCuq7dJoqOg5Hkv6cb03t5cflj+oCoB4XEf7BHVbo2dIffXBIPSDD500H9CiYm9yRMIYgQ9FyGlTa2GF1XS4u24iOfaVpy0hHy36BADPDjS5G6ilSBg84aQGJ/u1UUDM4uJkvS3nYkV4ES+ikHgns=
    username: AgBuPtWUZtMHotWq13GlILSRSNvLnk//dvrdEjHaBQwNmZHbHUF1emlgJhWmfqn7Tl+dEyDJLkyqXPQSJFk0Q9kqqFTmvjdWSdxfPRs8YyO2Mdcw9nhs41j90Q0vlGqNB1kUCRuSp1w6FdwYqVQF4iUXVCoPwsQZFBFgU7EftmuyRz6Wuq+eM8Qf5R+Ms/uH/jqIAMTdZANa0gKml1XCGdIPbj1EQdiaMMGIDTcoDr3NB6FN1zHLVZbH3/lUgJkhv4O+16DFU6WZA0ugXZ8yqVI+CLCUBkKTNHiwJX7Dz0ftycLzsxB2rHHBdTfTNLJxFon0QFKEtWlZGJHbye6gr9Te9LRJ9IBEVgRypm7tjSx/SZaJVrvCj3v33EcmvJIeZmOO+4uqlIryyZ8blxmjXC/LQVcn58nd4sfCaSe2gZI7JX5WU4DCNehRXoVw+hf0ckV8RfyG6A72EDBEzqX9bYswUib7JraYA3acmreQDxJD8DMM/ptk1r6OMqZ1taQAY/qqWqdtLFfPguL7+yqzNv+dhTS4nExAofY+RTy+jEsR4U/mGiQasprZVyptVB2Lp9vUcK6PIhQi/BajqhnyyF9RY9xcqZTxo4p3vv+oXwDYiJul6z1Z8nGT46DMkzzzE6uCcQTR6pjakvBnSwdkOWcMfAErVJoAsiB8uSA4EDo/AnGt8nQ9Y3PoVvU7oUGSt3bz6yDPJkgZL30=
  template:
    metadata:
      labels:
        rabbitmq.com/topology-operator: "true"
      name: rmq-user-admin-api
      namespace: banking-data
