---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rmq-user-core
  namespace: banking-data
spec:
  encryptedData:
    password: AgAGnsvnxAo4Tgxm0C8y4MMk6BQzQKXEnPbvuGCHj+IeKt1WUQPiu+HCLmpdOCLyS2Dn3DbPwkC6M7t9Y2tlCg36TWBV6Q/0YUx0FWFU/yYA9QDygBxriZtpjhu4am6545GxBOl6CE29ou58mMjhhnHCUzSN3+rZ/IST3hUkHcroVsXJG0SsJu8+jVzmaz+N08y67IneGZRjhoIN8nHSvsJfr/1s7NZndmi/UaMqW4Z3QyV0COAqIxhTWZ9nEP2pi8EjIaVZ57sXAV2WPkOtIuccJuUoTcQD5HHO2NVl2VYtYlx0hf5tt6whDG2uxK3H0+iAQQMCRTb28P/dWL2JnK913lDh2nAfvXR/XRbzMCWaFmaGvvwJcTeNoP8QqpgGaoAAufeh5RY7qTHkPwdhT1Chdasfh1ZIESijTQ0Da6yzz8mcTqhs9vGm/ZxDla+E79YGA+BQ1WKQxaUyhrzdt+xb95NEJkLPtI0r0PmSb2y3KpfyaBCvpLuz9iKtFdVS/92tSikKM9lxOb0uRfvpsobTNZTRigFKfWzJCz3hBd5N9hehvK1irUI8Od1Kmc+cYAYFTTWTznEFH5MJlOI857HSRFvyqpUtXrKLtBuoMGd9rzNAMRFRkebuVkueXkGG7Hwdo7SInpW0Oecv+uMUTXYVPjqpCLmV6NIXpPcf8wJLV0LGAwI8H9NGGfk2IWWUCvOWOf+MzikP/SyArqeDFGqBfSn6B9tUZ43UeXX79iolVDTKHhwZhRs2RyPQkjYj32w=
    username: AgB9EXbh6OJgJn2oDWPZiwztJbXF8g6olc3gq2aDtihg8kC9TQOVS07J0D4YxPEKzXOHY8UTDFIcUSwlIqja6yDiWP12rgqKjrnVHL4gxFyWF76dJukWD70pjRbVudyajJteW2iISmy31hX5bGnMwxGadExKoisUJCB2wDDTzQVaIVdgM8Z6JIjJLC7T5BzW1UdD9zMVOoxCq2A6PpK43ua9v4QySBXOv7SR8Vftnf4dJBI5C8kpbRHl0nDQkYIsrV8JS6UFQq3D4UDZoDdGrK0FGrFj0fNiU9O7v/OB2Nts6Iwxx54316c5PZxo2vxOqPZRK9ks5OLiwjvNxtpNMRnL9eV1qwNC54D950cY9XheSxiMcKBJinyA3dYvxI7oLKKGRhAzpDEXrXQj68rZ505iQTHcoYNq9B6N9nw8aR5AOppy73V3fMJTQi69jop/Mg5CDf0PUnD1twj6j+hz4HcNg2CSsNrZQrqhGuuVS4ipii9zASEPCpA3DcdcnCmdKpDAY6mLNMHZPmj/hcowtGryRa2ok46Wr/98KEHVn+/GK3RAvZhuJ1IGHkaSFHv4gY2z43wrPIQ9CJDQKCQhnWpTec+dGe0XnZBzcdGUzi6VW+aJieM9pg6CxoRezcy5vIkjwL+FUIxKt9vPG1h2xn7plTtJwnJw/arp6AkjRrQADGeIHGttk9+RcHRXCNw0rGM7wg+6
  template:
    metadata:
      labels:
        rabbitmq.com/topology-operator: "true"
      name: rmq-user-core
      namespace: banking-data
