---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-public-app
  namespace: banking-data
spec:
  encryptedData:
    password: AgALVVyfhMkw7hPZ0PbZU7PFlYuzePgStFPCQeHbs6LMbZTKEl8L+h4Qe5C5W+/WUmTTlpIvTD2iLKOMS8cQRmSA6MKQKXV65JNJtLBwl0cH6GzRUwv0dBcv+6d3BJuZ9zNCpp42apnlRBddfM98w1ZhscxiD80k9RDYPltY62YLjH+hPZHnHkku2O34DJERwvt9DzyyUXGB/en/B5uMnUHLv/ZbhS1souuAWK4hmSBYi88M++mAc5L8anh5lBXLh2zVRXQF47uujEn++jhs1Wlf7Cak0MdZWpS2rBitMzcCczByx0blhxY6DGVlkKSPY3ej7bkMqTmG+5BYQAw7dqMFU5IQ6mtCCJkmsaWig3zwoFc4oNH5WbadDEf4psnVmo1ZvGltcFaeLMDENC4VajitF+gGkRShhfWBBrt5eUja5r2s0cJvbLUfygRKU3E7MMYNisOVT7Bkeatb5lO2tLsRpT8MqOfrf4/7kN+K+ApL7avKhhwV+qioPPTj+EkEYsVx9Z1VkK42YsG1IMaMg8plHX10ok/6VplfbJaNu44p1o/MctHHehoPy5TO3HTP/6NcZK0zkLiFeQRR3sIwyU2VhuCybdLXs7JIaChO5UNBbA7mDBw5VQKDG7xZjrUBUswzyJIodskvG3dLpI42+lCxTZghI3MjVy7RhllR6vuJP3lhQ7ToXSuLyCGujwZ9p8LjYQit+AHiBPrN6B/VYbOc+tkaNGo02hdEfOiuz/3szvFeQ0J63DUAkGHh6IvSK5A=
    username: AgC7Vsgo11Z+SyMAYcn9y2niNG9UpFMdfGl4mGmUQpAskgNh2UU6lC/zlBlA2PDJWhxg3/wenHDLfU5/EoVfVXfN+AddXfKvvqJs16O21zl8Cd8u418cdH4Ljemt0YH4QBRILxmqyEFTFjGt5x6rYyc3TILhFp296pilTfFhVquIKrLuvi0SAseNZO4pVOLrlm6kEUG15bPqmLNxXIX38v1aSu9vzDrEsnuFtDNz3UCJIsniMUpqp8SUZeRIbnZYm64cvUWCt5un0od+nZLVoD2qyJCCtwGgDudq77DgLt6+Lj/uU7Sug90cQYaHyW7J8y9TIriFrl+VXpmwnHjJCvtM+8Wsk/74OQzOvvgLyZ5scjq2PI732iYhFX3t+Y89FNEdAiqvH6+s+duuDqKVmCjYcT8TZrkL8Z379Nf+/75xIX2aSQSkZRzHwRwCtoJknVj4/2k9xc4cmGPm3bZ1HrAU7p3O547zqpID3BCmg8TIRH6jU4kwidVYODTRSJqtB0BL1uUFonCJH7gtfFoLRB4n2QI95h+qlGULDBJU3pi58uQ9Ko6sUWL1rBaqhq7JTLvatuYjziFeKoWnkVaC0y7vacODF8zoNHpXEzjWIG2jnqsJO72gH+4rPXpWtJXI5BNMdgSBsiX6kffn1CmgydVmxDJPIpEKbCqC+EMD9qIYBOv1qjQzF6TMVZ9+e4Er/EsY+Jf/zXBg46h7
  template:
    metadata:
      name: pg-public-app
      namespace: banking-data
    type: kubernetes.io/basic-auth
