#!/usr/bin/env bash
# Generates Kubernetes objects from observability-as-code sources (spec §10). Output is committed; CI runs obs-gen-check.
#   observability/alerts/<f>.yaml → deploy/platform/observability/kind/rules/bg-<f>.yaml (PrometheusRule)
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/deploy/platform/observability/kind"

rm -rf "$OUT/rules"; mkdir -p "$OUT/rules"
for f in "$ROOT"/observability/alerts/*.yaml; do
  n=$(basename "$f" .yaml)
  {
    echo "# GENERATED by scripts/gen-observability.sh from observability/alerts/$n.yaml — do not edit."
    echo "apiVersion: monitoring.coreos.com/v1"
    echo "kind: PrometheusRule"
    echo "metadata:"
    echo "  name: bg-$n"
    echo "  namespace: monitoring"
    echo "  labels:"
    echo "    app.kubernetes.io/part-of: banking-go"
    echo "spec:"
    grep -v '^#' "$f" | sed 's/^/  /'
  } > "$OUT/rules/bg-$n.yaml"
done
echo "generated $(ls "$OUT/rules" | wc -l) PrometheusRule file(s)"
