apiVersion: v1
kind: Namespace
metadata:
  name: banking
  labels: {app.kubernetes.io/part-of: banking-go}
---
apiVersion: v1
kind: Namespace
metadata:
  name: banking-data
  labels: {app.kubernetes.io/part-of: banking-go}
